name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      deno_version: v1.x

    steps:
      - name: Setup Repository (${{github.event.repository.name}})
        uses: actions/checkout@v3

      - name: Setup Deno ${{env.deno_version}}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{env.deno_version}}

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A --unstable --check --reload --doc --allow-none
